server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:gapsidb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  version: 1.0.0
  candidato:
    name: Candidato 01
